class Product {
  final String id;
  final String name;
  final String brand;
  final double price;
  final double originalPrice;
  final String imageUrl;
  final String description;
  final String category;
  final String subcategory;
  final double rating;
  final int reviewCount;
  final bool inStock;

  const Product({
    required this.id,
    required this.name,
    required this.brand,
    required this.price,
    required this.originalPrice,
    required this.imageUrl,
    required this.description,
    required this.category,
    required this.subcategory,
    required this.rating,
    required this.reviewCount,
    required this.inStock,
  });

  int get discountPercentage {
    if (originalPrice <= price) return 0;
    return ((originalPrice - price) / originalPrice * 100).round();
  }

  String get formattedPrice => '₹${price.toStringAsFixed(0)}';

  String get formattedOriginalPrice =>
      '₹${originalPrice.toStringAsFixed(0)}';
}

const List<Product> sampleProducts = [

  // ============================================================
  // ELECTRONICS - 30
  // ============================================================

  Product(
    id: 'e1',
    name: 'Wireless Bluetooth Headphones',
    brand: 'boAt',
    price: 1499,
    originalPrice: 2999,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e',
    description: 'Wireless headphones with deep bass and long battery life.',
    category: 'Electronics',
    subcategory: 'Headphones',
    rating: 4.4,
    reviewCount: 1250,
    inStock: true,
  ),
  Product(
    id: 'e2',
    name: 'True Wireless Earbuds',
    brand: 'Noise',
    price: 1299,
    originalPrice: 2499,
    imageUrl: 'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1',
    description: 'Compact wireless earbuds with charging case.',
    category: 'Electronics',
    subcategory: 'Earbuds',
    rating: 4.3,
    reviewCount: 980,
    inStock: true,
  ),
  Product(
    id: 'e3',
    name: 'Smart Watch Series 5',
    brand: 'Fire-Boltt',
    price: 1799,
    originalPrice: 3999,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30',
    description: 'Smart watch with fitness tracking and notifications.',
    category: 'Electronics',
    subcategory: 'Smart Watches',
    rating: 4.2,
    reviewCount: 740,
    inStock: true,
  ),
  Product(
    id: 'e4',
    name: 'Portable Bluetooth Speaker',
    brand: 'JBL',
    price: 2499,
    originalPrice: 4999,
    imageUrl: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1',
    description: 'Portable speaker with powerful wireless audio.',
    category: 'Electronics',
    subcategory: 'Speakers',
    rating: 4.6,
    reviewCount: 1560,
    inStock: true,
  ),
  Product(
    id: 'e5',
    name: 'Wireless Gaming Mouse',
    brand: 'Logitech',
    price: 1899,
    originalPrice: 2999,
    imageUrl: 'https://images.unsplash.com/photo-1527814050087-3793815479db',
    description: 'High precision wireless gaming mouse.',
    category: 'Electronics',
    subcategory: 'Computer Accessories',
    rating: 4.5,
    reviewCount: 620,
    inStock: true,
  ),
  Product(
    id: 'e6',
    name: 'Mechanical Gaming Keyboard',
    brand: 'Redragon',
    price: 2799,
    originalPrice: 4499,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3',
    description: 'Mechanical keyboard for gaming and productivity.',
    category: 'Electronics',
    subcategory: 'Computer Accessories',
    rating: 4.5,
    reviewCount: 510,
    inStock: true,
  ),
  Product(
    id: 'e7',
    name: 'USB-C Fast Charger',
    brand: 'Samsung',
    price: 899,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0',
    description: 'Fast USB-C charger for phones and tablets.',
    category: 'Electronics',
    subcategory: 'Chargers & Cables',
    rating: 4.4,
    reviewCount: 890,
    inStock: true,
  ),
  Product(
    id: 'e8',
    name: 'Premium USB-C Cable',
    brand: 'Anker',
    price: 599,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1625842268584-8f3296236761',
    description: 'Durable fast charging USB-C cable.',
    category: 'Electronics',
    subcategory: 'Chargers & Cables',
    rating: 4.5,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'e9',
    name: 'Android Smartphone 5G',
    brand: 'OnePlus',
    price: 24999,
    originalPrice: 29999,
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9',
    description: 'Modern 5G smartphone with powerful performance.',
    category: 'Electronics',
    subcategory: 'Mobiles',
    rating: 4.5,
    reviewCount: 2100,
    inStock: true,
  ),
  Product(
    id: 'e10',
    name: 'Premium Smartphone',
    brand: 'Samsung',
    price: 32999,
    originalPrice: 39999,
    imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97',
    description: 'Premium smartphone with AMOLED display.',
    category: 'Electronics',
    subcategory: 'Mobiles',
    rating: 4.6,
    reviewCount: 1850,
    inStock: true,
  ),
  Product(
    id: 'e11',
    name: 'Budget Android Phone',
    brand: 'Redmi',
    price: 10999,
    originalPrice: 13999,
    imageUrl: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd',
    description: 'Affordable smartphone for everyday use.',
    category: 'Electronics',
    subcategory: 'Mobiles',
    rating: 4.2,
    reviewCount: 3200,
    inStock: true,
  ),
  Product(
    id: 'e12',
    name: '5G Smartphone Pro',
    brand: 'Realme',
    price: 17999,
    originalPrice: 21999,
    imageUrl: 'https://images.unsplash.com/photo-1556656793-08538906a9f8',
    description: 'Fast 5G smartphone with high refresh rate display.',
    category: 'Electronics',
    subcategory: 'Mobiles',
    rating: 4.3,
    reviewCount: 1450,
    inStock: true,
  ),
  Product(
    id: 'e13',
    name: 'Slim Laptop 15',
    brand: 'HP',
    price: 54999,
    originalPrice: 64999,
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853',
    description: 'Slim laptop for students and office work.',
    category: 'Electronics',
    subcategory: 'Laptops',
    rating: 4.4,
    reviewCount: 870,
    inStock: true,
  ),
  Product(
    id: 'e14',
    name: 'Performance Laptop',
    brand: 'Lenovo',
    price: 62999,
    originalPrice: 74999,
    imageUrl: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1',
    description: 'Powerful laptop for programming and productivity.',
    category: 'Electronics',
    subcategory: 'Laptops',
    rating: 4.5,
    reviewCount: 690,
    inStock: true,
  ),
  Product(
    id: 'e15',
    name: 'Gaming Laptop',
    brand: 'ASUS',
    price: 74999,
    originalPrice: 89999,
    imageUrl: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302',
    description: 'High-performance gaming laptop.',
    category: 'Electronics',
    subcategory: 'Laptops',
    rating: 4.6,
    reviewCount: 520,
    inStock: true,
  ),
  Product(
    id: 'e16',
    name: 'Student Laptop',
    brand: 'Acer',
    price: 42999,
    originalPrice: 49999,
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed',
    description: 'Reliable laptop for students.',
    category: 'Electronics',
    subcategory: 'Laptops',
    rating: 4.3,
    reviewCount: 740,
    inStock: true,
  ),
  Product(
    id: 'e17',
    name: '10 Inch Android Tablet',
    brand: 'Samsung',
    price: 15999,
    originalPrice: 19999,
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0',
    description: 'Large-screen tablet for studying and entertainment.',
    category: 'Electronics',
    subcategory: 'Tablets',
    rating: 4.4,
    reviewCount: 610,
    inStock: true,
  ),
  Product(
    id: 'e18',
    name: 'Premium Tablet',
    brand: 'Apple',
    price: 34999,
    originalPrice: 39999,
    imageUrl: 'https://images.unsplash.com/photo-1561154464-82e9adf32764',
    description: 'Premium tablet with powerful processor.',
    category: 'Electronics',
    subcategory: 'Tablets',
    rating: 4.7,
    reviewCount: 980,
    inStock: true,
  ),
  Product(
    id: 'e19',
    name: 'Noise Cancelling Headphones',
    brand: 'Sony',
    price: 6999,
    originalPrice: 9999,
    imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b',
    description: 'Headphones with active noise cancellation.',
    category: 'Electronics',
    subcategory: 'Headphones',
    rating: 4.7,
    reviewCount: 1250,
    inStock: true,
  ),
  Product(
    id: 'e20',
    name: 'Sports Wireless Earbuds',
    brand: 'Realme',
    price: 1699,
    originalPrice: 2999,
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df',
    description: 'Lightweight earbuds for workouts.',
    category: 'Electronics',
    subcategory: 'Earbuds',
    rating: 4.3,
    reviewCount: 830,
    inStock: true,
  ),
  Product(
    id: 'e21',
    name: 'Fitness Smartwatch',
    brand: 'Amazfit',
    price: 3999,
    originalPrice: 5999,
    imageUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1',
    description: 'Fitness smartwatch with activity tracking.',
    category: 'Electronics',
    subcategory: 'Smart Watches',
    rating: 4.5,
    reviewCount: 920,
    inStock: true,
  ),
  Product(
    id: 'e22',
    name: 'Smart Speaker',
    brand: 'Amazon',
    price: 2999,
    originalPrice: 4499,
    imageUrl: 'https://images.unsplash.com/photo-1589492477829-5e65395b66cc',
    description: 'Smart speaker for music and home control.',
    category: 'Electronics',
    subcategory: 'Speakers',
    rating: 4.4,
    reviewCount: 1100,
    inStock: true,
  ),
  Product(
    id: 'e23',
    name: 'Wireless Keyboard Mouse Combo',
    brand: 'HP',
    price: 1499,
    originalPrice: 2299,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3',
    description: 'Wireless keyboard and mouse combo.',
    category: 'Electronics',
    subcategory: 'Computer Accessories',
    rating: 4.2,
    reviewCount: 460,
    inStock: true,
  ),
  Product(
    id: 'e24',
    name: '1080p HD Webcam',
    brand: 'Logitech',
    price: 2499,
    originalPrice: 3499,
    imageUrl: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da',
    description: 'Full HD webcam for online meetings and classes.',
    category: 'Electronics',
    subcategory: 'Computer Accessories',
    rating: 4.4,
    reviewCount: 580,
    inStock: true,
  ),
  Product(
    id: 'e25',
    name: '65W GaN Fast Charger',
    brand: 'Anker',
    price: 2999,
    originalPrice: 3999,
    imageUrl: 'https://images.unsplash.com/photo-1625842268584-8f3296236761',
    description: 'Compact high-speed charger.',
    category: 'Electronics',
    subcategory: 'Chargers & Cables',
    rating: 4.6,
    reviewCount: 390,
    inStock: true,
  ),
  Product(
    id: 'e26',
    name: '4K Action Camera',
    brand: 'GoPro',
    price: 24999,
    originalPrice: 29999,
    imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f',
    description: 'Action camera for travel and adventure.',
    category: 'Electronics',
    subcategory: 'Cameras',
    rating: 4.6,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'e27',
    name: 'Mirrorless Digital Camera',
    brand: 'Canon',
    price: 58999,
    originalPrice: 69999,
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32',
    description: 'Mirrorless camera for photography.',
    category: 'Electronics',
    subcategory: 'Cameras',
    rating: 4.7,
    reviewCount: 350,
    inStock: true,
  ),
  Product(
    id: 'e28',
    name: '43 Inch Smart TV',
    brand: 'LG',
    price: 29999,
    originalPrice: 39999,
    imageUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6',
    description: '4K smart television with streaming apps.',
    category: 'Electronics',
    subcategory: 'Televisions',
    rating: 4.5,
    reviewCount: 780,
    inStock: true,
  ),
  Product(
    id: 'e29',
    name: '55 Inch 4K Smart TV',
    brand: 'Sony',
    price: 54999,
    originalPrice: 69999,
    imageUrl: 'https://images.unsplash.com/photo-1461151304267-38535e780c79',
    description: 'Large 4K smart television.',
    category: 'Electronics',
    subcategory: 'Televisions',
    rating: 4.7,
    reviewCount: 540,
    inStock: true,
  ),
  Product(
    id: 'e30',
    name: '10000mAh Power Bank',
    brand: 'MI',
    price: 999,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1609592424773-8c4d0e0a9e9b',
    description: 'Portable power bank with fast charging.',
    category: 'Electronics',
    subcategory: 'Power Banks',
    rating: 4.3,
    reviewCount: 1350,
    inStock: true,
  ),

  // ============================================================
  // FASHION - 30
  // ============================================================

  Product(
    id: 'f1',
    name: 'Classic Cotton T-Shirt',
    brand: 'Roadster',
    price: 599,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab',
    description: 'Comfortable cotton t-shirt for everyday wear.',
    category: 'Fashion',
    subcategory: 'Men',
    rating: 4.3,
    reviewCount: 1200,
    inStock: true,
  ),
  Product(
    id: 'f2',
    name: 'Slim Fit Casual Shirt',
    brand: 'Levis',
    price: 1199,
    originalPrice: 1999,
    imageUrl: 'https://images.unsplash.com/photo-1603252109303-2751441dd157',
    description: 'Stylish slim fit casual shirt.',
    category: 'Fashion',
    subcategory: 'Men',
    rating: 4.4,
    reviewCount: 850,
    inStock: true,
  ),
  Product(
    id: 'f3',
    name: 'Regular Fit Jeans',
    brand: 'Wrangler',
    price: 1499,
    originalPrice: 2499,
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d',
    description: 'Comfortable regular fit denim jeans.',
    category: 'Fashion',
    subcategory: 'Men',
    rating: 4.4,
    reviewCount: 930,
    inStock: true,
  ),
  Product(
    id: 'f4',
    name: 'Men Casual Kurta',
    brand: 'Manyavar',
    price: 999,
    originalPrice: 1799,
    imageUrl: 'https://images.unsplash.com/photo-1597983073493-88cd35cf93e8',
    description: 'Traditional cotton kurta for festive occasions.',
    category: 'Fashion',
    subcategory: 'Men',
    rating: 4.5,
    reviewCount: 670,
    inStock: true,
  ),
  Product(
    id: 'f5',
    name: 'Men Formal Trousers',
    brand: 'Allen Solly',
    price: 1299,
    originalPrice: 2199,
    imageUrl: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80',
    description: 'Smart formal trousers for office wear.',
    category: 'Fashion',
    subcategory: 'Men',
    rating: 4.2,
    reviewCount: 540,
    inStock: true,
  ),
  Product(
    id: 'f6',
    name: 'Floral Summer Dress',
    brand: 'Tokyo Talkies',
    price: 999,
    originalPrice: 1799,
    imageUrl: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446',
    description: 'Elegant floral dress for casual occasions.',
    category: 'Fashion',
    subcategory: 'Women',
    rating: 4.5,
    reviewCount: 1100,
    inStock: true,
  ),
  Product(
    id: 'f7',
    name: 'Designer Kurti',
    brand: 'Biba',
    price: 899,
    originalPrice: 1599,
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2',
    description: 'Beautiful ethnic kurti for women.',
    category: 'Fashion',
    subcategory: 'Women',
    rating: 4.4,
    reviewCount: 890,
    inStock: true,
  ),
  Product(
    id: 'f8',
    name: 'Printed Saree',
    brand: 'Sangria',
    price: 1299,
    originalPrice: 2299,
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c',
    description: 'Elegant printed saree with beautiful design.',
    category: 'Fashion',
    subcategory: 'Women',
    rating: 4.5,
    reviewCount: 740,
    inStock: true,
  ),
  Product(
    id: 'f9',
    name: 'Women Casual Top',
    brand: 'ONLY',
    price: 699,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3',
    description: 'Trendy casual top for everyday fashion.',
    category: 'Fashion',
    subcategory: 'Women',
    rating: 4.3,
    reviewCount: 620,
    inStock: true,
  ),
  Product(
    id: 'f10',
    name: 'Women Wide Leg Jeans',
    brand: 'H&M',
    price: 1399,
    originalPrice: 2299,
    imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246',
    description: 'Modern wide-leg jeans for women.',
    category: 'Fashion',
    subcategory: 'Women',
    rating: 4.4,
    reviewCount: 810,
    inStock: true,
  ),
  Product(
    id: 'f11',
    name: 'Women Handbag',
    brand: 'Lavie',
    price: 1299,
    originalPrice: 2499,
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3',
    description: 'Stylish handbag with spacious compartments.',
    category: 'Fashion',
    subcategory: 'Women',
    rating: 4.5,
    reviewCount: 920,
    inStock: true,
  ),
  Product(
    id: 'f12',
    name: 'Embroidered Anarkali Dress',
    brand: 'Aurelia',
    price: 1799,
    originalPrice: 2999,
    imageUrl: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1',
    description: 'Elegant embroidered ethnic dress.',
    category: 'Fashion',
    subcategory: 'Women',
    rating: 4.6,
    reviewCount: 510,
    inStock: true,
  ),
  Product(
    id: 'f13',
    name: 'Boys Printed T-Shirt',
    brand: 'Puma',
    price: 499,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4',
    description: 'Comfortable printed t-shirt for boys.',
    category: 'Fashion',
    subcategory: 'Kids',
    rating: 4.3,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'f14',
    name: 'Girls Party Dress',
    brand: 'Allen Solly Junior',
    price: 899,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42',
    description: 'Beautiful party dress for girls.',
    category: 'Fashion',
    subcategory: 'Kids',
    rating: 4.6,
    reviewCount: 520,
    inStock: true,
  ),
  Product(
    id: 'f15',
    name: 'Kids Denim Jacket',
    brand: 'Pepe Jeans',
    price: 999,
    originalPrice: 1799,
    imageUrl: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b',
    description: 'Trendy denim jacket for kids.',
    category: 'Fashion',
    subcategory: 'Kids',
    rating: 4.4,
    reviewCount: 380,
    inStock: true,
  ),
  Product(
    id: 'f16',
    name: 'Boys Casual Shirt',
    brand: 'U.S. Polo',
    price: 699,
    originalPrice: 1299,
    imageUrl: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8',
    description: 'Smart casual shirt for boys.',
    category: 'Fashion',
    subcategory: 'Kids',
    rating: 4.3,
    reviewCount: 410,
    inStock: true,
  ),
  Product(
    id: 'f17',
    name: 'Kids Hoodie',
    brand: 'H&M Kids',
    price: 799,
    originalPrice: 1399,
    imageUrl: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4',
    description: 'Warm and comfortable hoodie for kids.',
    category: 'Fashion',
    subcategory: 'Kids',
    rating: 4.4,
    reviewCount: 360,
    inStock: true,
  ),
  Product(
    id: 'f18',
    name: 'Men Polo T-Shirt',
    brand: 'U.S. Polo',
    price: 899,
    originalPrice: 1599,
    imageUrl: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d',
    description: 'Classic polo t-shirt for men.',
    category: 'Fashion',
    subcategory: 'Men',
    rating: 4.5,
    reviewCount: 780,
    inStock: true,
  ),
  Product(
    id: 'f19',
    name: 'Men Linen Shirt',
    brand: 'Van Heusen',
    price: 1399,
    originalPrice: 2299,
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c',
    description: 'Breathable linen shirt for summer.',
    category: 'Fashion',
    subcategory: 'Men',
    rating: 4.4,
    reviewCount: 510,
    inStock: true,
  ),
  Product(
    id: 'f20',
    name: 'Men Denim Jacket',
    brand: 'Levis',
    price: 1999,
    originalPrice: 3499,
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5',
    description: 'Classic denim jacket for casual styling.',
    category: 'Fashion',
    subcategory: 'Men',
    rating: 4.5,
    reviewCount: 620,
    inStock: true,
  ),
  Product(
    id: 'f21',
    name: 'Women Cotton Kurta',
    brand: 'W',
    price: 999,
    originalPrice: 1699,
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2',
    description: 'Comfortable cotton kurta for everyday wear.',
    category: 'Fashion',
    subcategory: 'Women',
    rating: 4.4,
    reviewCount: 720,
    inStock: true,
  ),
  Product(
    id: 'f22',
    name: 'Women Palazzo Set',
    brand: 'Libas',
    price: 1499,
    originalPrice: 2499,
    imageUrl: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1',
    description: 'Elegant ethnic palazzo set.',
    category: 'Fashion',
    subcategory: 'Women',
    rating: 4.5,
    reviewCount: 610,
    inStock: true,
  ),
  Product(
    id: 'f23',
    name: 'Women Casual Jeans',
    brand: 'Levis',
    price: 1599,
    originalPrice: 2799,
    imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246',
    description: 'Comfortable casual jeans for women.',
    category: 'Fashion',
    subcategory: 'Women',
    rating: 4.4,
    reviewCount: 850,
    inStock: true,
  ),
  Product(
    id: 'f24',
    name: 'Women Blazer',
    brand: 'Zara',
    price: 2299,
    originalPrice: 3999,
    imageUrl: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3',
    description: 'Smart blazer for professional styling.',
    category: 'Fashion',
    subcategory: 'Women',
    rating: 4.3,
    reviewCount: 340,
    inStock: true,
  ),
  Product(
    id: 'f25',
    name: 'Kids Cotton Shorts',
    brand: 'Max',
    price: 499,
    originalPrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b',
    description: 'Soft cotton shorts for kids.',
    category: 'Fashion',
    subcategory: 'Kids',
    rating: 4.2,
    reviewCount: 280,
    inStock: true,
  ),
  Product(
    id: 'f26',
    name: 'Kids Printed Kurta',
    brand: 'Manyavar',
    price: 699,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1597983073493-88cd35cf93e8',
    description: 'Festive printed kurta for kids.',
    category: 'Fashion',
    subcategory: 'Kids',
    rating: 4.5,
    reviewCount: 390,
    inStock: true,
  ),
  Product(
    id: 'f27',
    name: 'Men Track Pants',
    brand: 'Adidas',
    price: 999,
    originalPrice: 1799,
    imageUrl: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea',
    description: 'Comfortable track pants for workouts.',
    category: 'Fashion',
    subcategory: 'Men',
    rating: 4.4,
    reviewCount: 560,
    inStock: true,
  ),
  Product(
    id: 'f28',
    name: 'Women Jumpsuit',
    brand: 'Mango',
    price: 1599,
    originalPrice: 2799,
    imageUrl: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b',
    description: 'Stylish modern jumpsuit for women.',
    category: 'Fashion',
    subcategory: 'Women',
    rating: 4.4,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'f29',
    name: 'Kids Winter Sweater',
    brand: 'Mothercare',
    price: 799,
    originalPrice: 1399,
    imageUrl: 'https://images.unsplash.com/photo-1519457431-44ccd64a579b',
    description: 'Warm winter sweater for children.',
    category: 'Fashion',
    subcategory: 'Kids',
    rating: 4.5,
    reviewCount: 310,
    inStock: true,
  ),
  Product(
    id: 'f30',
    name: 'Men Designer Kurta Set',
    brand: 'Manyavar',
    price: 1999,
    originalPrice: 3499,
    imageUrl: 'https://images.unsplash.com/photo-1597983073493-88cd35cf93e8',
    description: 'Traditional designer kurta set.',
    category: 'Fashion',
    subcategory: 'Men',
    rating: 4.6,
    reviewCount: 470,
    inStock: true,
  ),

  // ============================================================
  // JEWELLERY - 30
  // ============================================================

  Product(
    id: 'j1',
    name: 'Gold Plated Necklace',
    brand: 'Zaveri Pearls',
    price: 799,
    originalPrice: 1599,
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f',
    description: 'Elegant gold plated necklace.',
    category: 'Jewellery',
    subcategory: 'Necklaces',
    rating: 4.5,
    reviewCount: 780,
    inStock: true,
  ),
  Product(
    id: 'j2',
    name: 'Pearl Necklace',
    brand: 'Sukkhi',
    price: 999,
    originalPrice: 1999,
    imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338',
    description: 'Classic pearl necklace for special occasions.',
    category: 'Jewellery',
    subcategory: 'Necklaces',
    rating: 4.6,
    reviewCount: 560,
    inStock: true,
  ),
  Product(
    id: 'j3',
    name: 'Artificial Diamond Necklace',
    brand: 'Jewels Galaxy',
    price: 1299,
    originalPrice: 2499,
    imageUrl: 'https://images.unsplash.com/photo-1617038220319-276d3cfab638',
    description: 'Sparkling necklace for party wear.',
    category: 'Jewellery',
    subcategory: 'Necklaces',
    rating: 4.4,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'j4',
    name: 'Traditional Jhumka Earrings',
    brand: 'Zaveri Pearls',
    price: 499,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908',
    description: 'Traditional Indian jhumka earrings.',
    category: 'Jewellery',
    subcategory: 'Earrings',
    rating: 4.7,
    reviewCount: 1100,
    inStock: true,
  ),
  Product(
    id: 'j5',
    name: 'Pearl Drop Earrings',
    brand: 'Sukkhi',
    price: 599,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236',
    description: 'Elegant pearl drop earrings.',
    category: 'Jewellery',
    subcategory: 'Earrings',
    rating: 4.5,
    reviewCount: 620,
    inStock: true,
  ),
  Product(
    id: 'j6',
    name: 'Stud Earrings',
    brand: 'Voylla',
    price: 399,
    originalPrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1588444650700-6f3e6c2b0b0a',
    description: 'Simple everyday stud earrings.',
    category: 'Jewellery',
    subcategory: 'Earrings',
    rating: 4.3,
    reviewCount: 510,
    inStock: true,
  ),
  Product(
    id: 'j7',
    name: 'Gold Plated Bangles',
    brand: 'Jewels Galaxy',
    price: 699,
    originalPrice: 1299,
    imageUrl: 'https://images.unsplash.com/photo-1611652022419-a9419f74343d',
    description: 'Beautiful gold plated bangles.',
    category: 'Jewellery',
    subcategory: 'Bangles',
    rating: 4.5,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'j8',
    name: 'Designer Bracelet',
    brand: 'Mia',
    price: 899,
    originalPrice: 1599,
    imageUrl: 'https://images.unsplash.com/photo-1619119069152-a2b331eb392a',
    description: 'Stylish bracelet for modern outfits.',
    category: 'Jewellery',
    subcategory: 'Bracelets',
    rating: 4.4,
    reviewCount: 390,
    inStock: true,
  ),
  Product(
    id: 'j9',
    name: 'Artificial Gold Ring',
    brand: 'Voylla',
    price: 299,
    originalPrice: 599,
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e',
    description: 'Elegant adjustable fashion ring.',
    category: 'Jewellery',
    subcategory: 'Rings',
    rating: 4.3,
    reviewCount: 350,
    inStock: true,
  ),
  Product(
    id: 'j10',
    name: 'Stone Studded Ring',
    brand: 'Zaveri Pearls',
    price: 499,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1603561596112-db9f6f7e8e14',
    description: 'Beautiful stone studded ring.',
    category: 'Jewellery',
    subcategory: 'Rings',
    rating: 4.5,
    reviewCount: 420,
    inStock: true,
  ),
  Product(
    id: 'j11',
    name: 'Silver Look Necklace',
    brand: 'Sukkhi',
    price: 699,
    originalPrice: 1299,
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f',
    description: 'Elegant silver look necklace.',
    category: 'Jewellery',
    subcategory: 'Necklaces',
    rating: 4.4,
    reviewCount: 390,
    inStock: true,
  ),
  Product(
    id: 'j12',
    name: 'Choker Necklace',
    brand: 'Voylla',
    price: 599,
    originalPrice: 1099,
    imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338',
    description: 'Modern choker necklace.',
    category: 'Jewellery',
    subcategory: 'Necklaces',
    rating: 4.3,
    reviewCount: 480,
    inStock: true,
  ),
  Product(
    id: 'j13',
    name: 'Oxidised Earrings',
    brand: 'Karatcart',
    price: 349,
    originalPrice: 699,
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908',
    description: 'Trendy oxidised earrings.',
    category: 'Jewellery',
    subcategory: 'Earrings',
    rating: 4.6,
    reviewCount: 710,
    inStock: true,
  ),
  Product(
    id: 'j14',
    name: 'Hoop Earrings',
    brand: 'Accessorize',
    price: 399,
    originalPrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236',
    description: 'Classic hoop earrings.',
    category: 'Jewellery',
    subcategory: 'Earrings',
    rating: 4.4,
    reviewCount: 520,
    inStock: true,
  ),
  Product(
    id: 'j15',
    name: 'Charm Bracelet',
    brand: 'Mia',
    price: 749,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1619119069152-a2b331eb392a',
    description: 'Beautiful charm bracelet.',
    category: 'Jewellery',
    subcategory: 'Bracelets',
    rating: 4.5,
    reviewCount: 360,
    inStock: true,
  ),
  Product(
    id: 'j16',
    name: 'Beaded Bracelet',
    brand: 'Voylla',
    price: 299,
    originalPrice: 599,
    imageUrl: 'https://images.unsplash.com/photo-1611652022419-a9419f74343d',
    description: 'Colorful beaded bracelet.',
    category: 'Jewellery',
    subcategory: 'Bracelets',
    rating: 4.2,
    reviewCount: 280,
    inStock: true,
  ),
  Product(
    id: 'j17',
    name: 'Traditional Bangles Set',
    brand: 'Sukkhi',
    price: 599,
    originalPrice: 1099,
    imageUrl: 'https://images.unsplash.com/photo-1611652022419-a9419f74343d',
    description: 'Traditional bangles set.',
    category: 'Jewellery',
    subcategory: 'Bangles',
    rating: 4.5,
    reviewCount: 590,
    inStock: true,
  ),
  Product(
    id: 'j18',
    name: 'Designer Bangles',
    brand: 'Zaveri Pearls',
    price: 799,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1611652022419-a9419f74343d',
    description: 'Designer bangle set for festive wear.',
    category: 'Jewellery',
    subcategory: 'Bangles',
    rating: 4.4,
    reviewCount: 420,
    inStock: true,
  ),
  Product(
    id: 'j19',
    name: 'Minimal Gold Ring',
    brand: 'Mia',
    price: 449,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e',
    description: 'Minimal everyday fashion ring.',
    category: 'Jewellery',
    subcategory: 'Rings',
    rating: 4.5,
    reviewCount: 330,
    inStock: true,
  ),
  Product(
    id: 'j20',
    name: 'Couple Ring Set',
    brand: 'Voylla',
    price: 699,
    originalPrice: 1299,
    imageUrl: 'https://images.unsplash.com/photo-1603561596112-db9f6f7e8e14',
    description: 'Matching couple ring set.',
    category: 'Jewellery',
    subcategory: 'Rings',
    rating: 4.4,
    reviewCount: 410,
    inStock: true,
  ),
  Product(
    id: 'j21',
    name: 'Temple Jewellery Set',
    brand: 'Zaveri Pearls',
    price: 1499,
    originalPrice: 2999,
    imageUrl: 'https://images.unsplash.com/photo-1617038220319-276d3cfab638',
    description: 'Traditional temple jewellery set.',
    category: 'Jewellery',
    subcategory: 'Necklaces',
    rating: 4.7,
    reviewCount: 280,
    inStock: true,
  ),
  Product(
    id: 'j22',
    name: 'Kundan Necklace Set',
    brand: 'Sukkhi',
    price: 1799,
    originalPrice: 3499,
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f',
    description: 'Elegant Kundan jewellery set.',
    category: 'Jewellery',
    subcategory: 'Necklaces',
    rating: 4.6,
    reviewCount: 310,
    inStock: true,
  ),
  Product(
    id: 'j23',
    name: 'Floral Earrings',
    brand: 'Voylla',
    price: 449,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908',
    description: 'Beautiful floral earrings.',
    category: 'Jewellery',
    subcategory: 'Earrings',
    rating: 4.3,
    reviewCount: 290,
    inStock: true,
  ),
  Product(
    id: 'j24',
    name: 'Crystal Earrings',
    brand: 'Accessorize',
    price: 549,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236',
    description: 'Sparkling crystal earrings.',
    category: 'Jewellery',
    subcategory: 'Earrings',
    rating: 4.5,
    reviewCount: 380,
    inStock: true,
  ),
  Product(
    id: 'j25',
    name: 'Pearl Bracelet',
    brand: 'Mia',
    price: 649,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1619119069152-a2b331eb392a',
    description: 'Elegant pearl bracelet.',
    category: 'Jewellery',
    subcategory: 'Bracelets',
    rating: 4.6,
    reviewCount: 270,
    inStock: true,
  ),
  Product(
    id: 'j26',
    name: 'Heart Bracelet',
    brand: 'Voylla',
    price: 499,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1611652022419-a9419f74343d',
    description: 'Heart design bracelet.',
    category: 'Jewellery',
    subcategory: 'Bracelets',
    rating: 4.3,
    reviewCount: 310,
    inStock: true,
  ),
  Product(
    id: 'j27',
    name: 'Statement Ring',
    brand: 'Karatcart',
    price: 399,
    originalPrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e',
    description: 'Bold statement fashion ring.',
    category: 'Jewellery',
    subcategory: 'Rings',
    rating: 4.4,
    reviewCount: 240,
    inStock: true,
  ),
  Product(
    id: 'j28',
    name: 'Adjustable Fashion Ring',
    brand: 'Voylla',
    price: 299,
    originalPrice: 599,
    imageUrl: 'https://images.unsplash.com/photo-1603561596112-db9f6f7e8e14',
    description: 'Adjustable stylish fashion ring.',
    category: 'Jewellery',
    subcategory: 'Rings',
    rating: 4.2,
    reviewCount: 210,
    inStock: true,
  ),
  Product(
    id: 'j29',
    name: 'Festive Jewellery Combo',
    brand: 'Sukkhi',
    price: 1999,
    originalPrice: 3999,
    imageUrl: 'https://images.unsplash.com/photo-1617038220319-276d3cfab638',
    description: 'Complete jewellery combo for festive occasions.',
    category: 'Jewellery',
    subcategory: 'Jewellery Sets',
    rating: 4.6,
    reviewCount: 350,
    inStock: true,
  ),
  Product(
    id: 'j30',
    name: 'Bridal Jewellery Set',
    brand: 'Zaveri Pearls',
    price: 2499,
    originalPrice: 4999,
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f',
    description: 'Beautiful bridal-inspired jewellery set.',
    category: 'Jewellery',
    subcategory: 'Jewellery Sets',
    rating: 4.7,
    reviewCount: 290,
    inStock: true,
  ),

  // ============================================================
  // HOME & LIVING - 30
  // ============================================================

  Product(
    id: 'h1',
    name: 'Modern Table Lamp',
    brand: 'Philips',
    price: 799,
    originalPrice: 1299,
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c',
    description: 'Modern decorative table lamp.',
    category: 'Home & Living',
    subcategory: 'Home Decor',
    rating: 4.4,
    reviewCount: 540,
    inStock: true,
  ),
  Product(
    id: 'h2',
    name: 'Decorative Wall Clock',
    brand: 'Random',
    price: 699,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c',
    description: 'Elegant wall clock for home decoration.',
    category: 'Home & Living',
    subcategory: 'Wall Decor',
    rating: 4.3,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'h3',
    name: 'Artificial Green Plant',
    brand: 'Home Centre',
    price: 499,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411',
    description: 'Low-maintenance artificial indoor plant.',
    category: 'Home & Living',
    subcategory: 'Home Decor',
    rating: 4.5,
    reviewCount: 680,
    inStock: true,
  ),
  Product(
    id: 'h4',
    name: 'Decorative Cushion Set',
    brand: 'Spaces',
    price: 599,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2',
    description: 'Soft decorative cushion set.',
    category: 'Home & Living',
    subcategory: 'Cushions',
    rating: 4.4,
    reviewCount: 390,
    inStock: true,
  ),
  Product(
    id: 'h5',
    name: 'Printed Cushion Covers',
    brand: 'Story@Home',
    price: 399,
    originalPrice: 699,
    imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0',
    description: 'Beautiful printed cushion covers.',
    category: 'Home & Living',
    subcategory: 'Cushions',
    rating: 4.3,
    reviewCount: 320,
    inStock: true,
  ),
  Product(
    id: 'h6',
    name: 'King Size Bedsheet',
    brand: 'Portico',
    price: 899,
    originalPrice: 1599,
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7',
    description: 'Soft printed king size bedsheet.',
    category: 'Home & Living',
    subcategory: 'Bedsheets',
    rating: 4.5,
    reviewCount: 740,
    inStock: true,
  ),
  Product(
    id: 'h7',
    name: 'Floral Bedsheet',
    brand: 'Spaces',
    price: 799,
    originalPrice: 1399,
    imageUrl: 'https://images.unsplash.com/photo-1616627561950-9f746e330187',
    description: 'Beautiful floral bedsheet.',
    category: 'Home & Living',
    subcategory: 'Bedsheets',
    rating: 4.4,
    reviewCount: 620,
    inStock: true,
  ),
  Product(
    id: 'h8',
    name: 'Blackout Curtains',
    brand: 'DDecor',
    price: 1199,
    originalPrice: 1999,
    imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6',
    description: 'Premium blackout curtains.',
    category: 'Home & Living',
    subcategory: 'Curtains',
    rating: 4.5,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'h9',
    name: 'Storage Organizer',
    brand: 'Solimo',
    price: 499,
    originalPrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7',
    description: 'Multipurpose home storage organizer.',
    category: 'Home & Living',
    subcategory: 'Storage',
    rating: 4.3,
    reviewCount: 510,
    inStock: true,
  ),
  Product(
    id: 'h10',
    name: 'Decorative Mirror',
    brand: 'Home Centre',
    price: 1299,
    originalPrice: 2199,
    imageUrl: 'https://images.unsplash.com/photo-1618220179428-22790b461013',
    description: 'Modern decorative wall mirror.',
    category: 'Home & Living',
    subcategory: 'Wall Decor',
    rating: 4.5,
    reviewCount: 390,
    inStock: true,
  ),
  Product(
    id: 'h11',
    name: 'Ceramic Flower Vase',
    brand: 'Home Centre',
    price: 599,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1581783898377-1c85bf937427',
    description: 'Elegant ceramic vase for home decor.',
    category: 'Home & Living',
    subcategory: 'Home Decor',
    rating: 4.6,
    reviewCount: 420,
    inStock: true,
  ),
  Product(
    id: 'h12',
    name: 'Scented Candle Set',
    brand: 'The Better Home',
    price: 449,
    originalPrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1603006905003-be475563bc59',
    description: 'Relaxing scented candle set.',
    category: 'Home & Living',
    subcategory: 'Home Decor',
    rating: 4.5,
    reviewCount: 570,
    inStock: true,
  ),
  Product(
    id: 'h13',
    name: 'Soft Sofa Cushion',
    brand: 'Spaces',
    price: 349,
    originalPrice: 599,
    imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2',
    description: 'Soft comfortable sofa cushion.',
    category: 'Home & Living',
    subcategory: 'Cushions',
    rating: 4.3,
    reviewCount: 330,
    inStock: true,
  ),
  Product(
    id: 'h14',
    name: 'Velvet Cushion Set',
    brand: 'Story@Home',
    price: 699,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0',
    description: 'Premium velvet cushion set.',
    category: 'Home & Living',
    subcategory: 'Cushions',
    rating: 4.5,
    reviewCount: 410,
    inStock: true,
  ),
  Product(
    id: 'h15',
    name: 'Cotton Double Bedsheet',
    brand: 'Bombay Dyeing',
    price: 699,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1616627561950-9f746e330187',
    description: 'Soft cotton double bedsheet.',
    category: 'Home & Living',
    subcategory: 'Bedsheets',
    rating: 4.4,
    reviewCount: 520,
    inStock: true,
  ),
  Product(
    id: 'h16',
    name: 'King Size Printed Bedsheet',
    brand: 'Portico',
    price: 999,
    originalPrice: 1799,
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7',
    description: 'Premium printed king size bedsheet.',
    category: 'Home & Living',
    subcategory: 'Bedsheets',
    rating: 4.6,
    reviewCount: 640,
    inStock: true,
  ),
  Product(
    id: 'h17',
    name: 'Sheer Window Curtains',
    brand: 'DDecor',
    price: 899,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6',
    description: 'Elegant sheer curtains.',
    category: 'Home & Living',
    subcategory: 'Curtains',
    rating: 4.4,
    reviewCount: 380,
    inStock: true,
  ),
  Product(
    id: 'h18',
    name: 'Door Curtains',
    brand: 'Spaces',
    price: 799,
    originalPrice: 1299,
    imageUrl: 'https://images.unsplash.com/photo-1618220179428-22790b461013',
    description: 'Stylish curtains for doors.',
    category: 'Home & Living',
    subcategory: 'Curtains',
    rating: 4.3,
    reviewCount: 340,
    inStock: true,
  ),
  Product(
    id: 'h19',
    name: 'Plastic Storage Boxes',
    brand: 'Milton',
    price: 599,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7',
    description: 'Multipurpose storage box set.',
    category: 'Home & Living',
    subcategory: 'Storage',
    rating: 4.2,
    reviewCount: 450,
    inStock: true,
  ),
  Product(
    id: 'h20',
    name: 'Kitchen Storage Rack',
    brand: 'HomeStrap',
    price: 799,
    originalPrice: 1299,
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f',
    description: 'Space-saving kitchen storage rack.',
    category: 'Home & Living',
    subcategory: 'Storage',
    rating: 4.4,
    reviewCount: 510,
    inStock: true,
  ),
  Product(
    id: 'h21',
    name: 'LED Decorative Lamp',
    brand: 'Philips',
    price: 999,
    originalPrice: 1699,
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c',
    description: 'Decorative LED lamp.',
    category: 'Home & Living',
    subcategory: 'Lighting',
    rating: 4.5,
    reviewCount: 390,
    inStock: true,
  ),
  Product(
    id: 'h22',
    name: 'Bedside Lamp',
    brand: 'Wipro',
    price: 699,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15',
    description: 'Elegant bedside lamp.',
    category: 'Home & Living',
    subcategory: 'Lighting',
    rating: 4.4,
    reviewCount: 460,
    inStock: true,
  ),
  Product(
    id: 'h23',
    name: 'Wall Art Set',
    brand: 'Home Centre',
    price: 899,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1549490349-8643362247b5',
    description: 'Decorative wall art set.',
    category: 'Home & Living',
    subcategory: 'Wall Decor',
    rating: 4.5,
    reviewCount: 270,
    inStock: true,
  ),
  Product(
    id: 'h24',
    name: 'Photo Frame Set',
    brand: 'Random',
    price: 499,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38',
    description: 'Decorative photo frame set.',
    category: 'Home & Living',
    subcategory: 'Wall Decor',
    rating: 4.4,
    reviewCount: 320,
    inStock: true,
  ),
  Product(
    id: 'h25',
    name: 'Decorative Plant Pot',
    brand: 'Home Centre',
    price: 299,
    originalPrice: 499,
    imageUrl: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411',
    description: 'Modern decorative plant pot.',
    category: 'Home & Living',
    subcategory: 'Home Decor',
    rating: 4.3,
    reviewCount: 280,
    inStock: true,
  ),
  Product(
    id: 'h26',
    name: 'Fleece Blanket',
    brand: 'Spaces',
    price: 899,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2',
    description: 'Warm soft fleece blanket.',
    category: 'Home & Living',
    subcategory: 'Bedding',
    rating: 4.6,
    reviewCount: 510,
    inStock: true,
  ),
  Product(
    id: 'h27',
    name: 'Bathroom Organizer',
    brand: 'Solimo',
    price: 399,
    originalPrice: 699,
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a',
    description: 'Compact bathroom organizer.',
    category: 'Home & Living',
    subcategory: 'Storage',
    rating: 4.2,
    reviewCount: 260,
    inStock: true,
  ),
  Product(
    id: 'h28',
    name: 'Laundry Basket',
    brand: 'Milton',
    price: 699,
    originalPrice: 1099,
    imageUrl: 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c',
    description: 'Large laundry basket for home.',
    category: 'Home & Living',
    subcategory: 'Storage',
    rating: 4.3,
    reviewCount: 350,
    inStock: true,
  ),
  Product(
    id: 'h29',
    name: 'Decorative Table Clock',
    brand: 'Random',
    price: 549,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c',
    description: 'Stylish decorative table clock.',
    category: 'Home & Living',
    subcategory: 'Home Decor',
    rating: 4.4,
    reviewCount: 290,
    inStock: true,
  ),
  Product(
    id: 'h30',
    name: 'Premium Floor Lamp',
    brand: 'Philips',
    price: 1599,
    originalPrice: 2499,
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c',
    description: 'Premium floor lamp for modern homes.',
    category: 'Home & Living',
    subcategory: 'Lighting',
    rating: 4.6,
    reviewCount: 340,
    inStock: true,
  ),

  // ============================================================
  // FLOWERS & GIFTS - 30
  // ============================================================

  Product(
    id: 'g1',
    name: 'Red Rose Bouquet',
    brand: 'FlowerAura',
    price: 599,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946',
    description: 'Fresh red roses beautifully arranged.',
    category: 'Flowers & Gifts',
    subcategory: 'Flower Bouquets',
    rating: 4.7,
    reviewCount: 920,
    inStock: true,
  ),
  Product(
    id: 'g2',
    name: 'Pink Rose Bouquet',
    brand: 'Ferns N Petals',
    price: 699,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9',
    description: 'Beautiful pink roses for special occasions.',
    category: 'Flowers & Gifts',
    subcategory: 'Flower Bouquets',
    rating: 4.6,
    reviewCount: 710,
    inStock: true,
  ),
  Product(
    id: 'g3',
    name: 'Mixed Flower Bouquet',
    brand: 'FlowerAura',
    price: 799,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1523438885200-e635ba2c371e',
    description: 'Colorful mixed flower bouquet.',
    category: 'Flowers & Gifts',
    subcategory: 'Flower Bouquets',
    rating: 4.7,
    reviewCount: 630,
    inStock: true,
  ),
  Product(
    id: 'g4',
    name: 'Birthday Gift Hamper',
    brand: 'IGP',
    price: 999,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48',
    description: 'Special birthday gift hamper.',
    category: 'Flowers & Gifts',
    subcategory: 'Gift Hampers',
    rating: 4.5,
    reviewCount: 520,
    inStock: true,
  ),
  Product(
    id: 'g5',
    name: 'Chocolate Gift Box',
    brand: 'Cadbury',
    price: 699,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b',
    description: 'Premium chocolate gift box.',
    category: 'Flowers & Gifts',
    subcategory: 'Chocolates',
    rating: 4.6,
    reviewCount: 850,
    inStock: true,
  ),
  Product(
    id: 'g6',
    name: 'Anniversary Flower Combo',
    brand: 'Ferns N Petals',
    price: 1299,
    originalPrice: 1799,
    imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946',
    description: 'Romantic flowers for anniversaries.',
    category: 'Flowers & Gifts',
    subcategory: 'Anniversary Gifts',
    rating: 4.8,
    reviewCount: 490,
    inStock: true,
  ),
  Product(
    id: 'g7',
    name: 'Love Rose Basket',
    brand: 'FlowerAura',
    price: 1099,
    originalPrice: 1599,
    imageUrl: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9',
    description: 'Romantic rose basket.',
    category: 'Flowers & Gifts',
    subcategory: 'Anniversary Gifts',
    rating: 4.7,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'g8',
    name: 'Personalized Photo Frame',
    brand: 'IGP',
    price: 499,
    originalPrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38',
    description: 'Personalized photo frame gift.',
    category: 'Flowers & Gifts',
    subcategory: 'Personalized Gifts',
    rating: 4.5,
    reviewCount: 610,
    inStock: true,
  ),
  Product(
    id: 'g9',
    name: 'Personalized Mug',
    brand: 'IGP',
    price: 349,
    originalPrice: 599,
    imageUrl: 'https://images.unsplash.com/photo-1514228742587-6b1558fcf93a',
    description: 'Custom photo printed mug.',
    category: 'Flowers & Gifts',
    subcategory: 'Personalized Gifts',
    rating: 4.4,
    reviewCount: 740,
    inStock: true,
  ),
  Product(
    id: 'g10',
    name: 'Greeting Card Set',
    brand: 'Archies',
    price: 299,
    originalPrice: 499,
    imageUrl: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0',
    description: 'Beautiful greeting cards for special occasions.',
    category: 'Flowers & Gifts',
    subcategory: 'Greeting Cards',
    rating: 4.3,
    reviewCount: 320,
    inStock: true,
  ),
  Product(
    id: 'g11',
    name: 'Premium Chocolate Basket',
    brand: 'Cadbury',
    price: 899,
    originalPrice: 1299,
    imageUrl: 'https://images.unsplash.com/photo-1575377427642-087cf684f29d',
    description: 'Premium assorted chocolate basket.',
    category: 'Flowers & Gifts',
    subcategory: 'Chocolates',
    rating: 4.7,
    reviewCount: 620,
    inStock: true,
  ),
  Product(
    id: 'g12',
    name: 'Luxury Flower Box',
    brand: 'Ferns N Petals',
    price: 1499,
    originalPrice: 1999,
    imageUrl: 'https://images.unsplash.com/photo-1487070183336-b863922373d4',
    description: 'Luxury flowers arranged in a box.',
    category: 'Flowers & Gifts',
    subcategory: 'Flower Bouquets',
    rating: 4.8,
    reviewCount: 390,
    inStock: true,
  ),
  Product(
    id: 'g13',
    name: 'Sunflower Bouquet',
    brand: 'FlowerAura',
    price: 649,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1597848212624-e19d4f6d6c4c',
    description: 'Bright sunflower bouquet.',
    category: 'Flowers & Gifts',
    subcategory: 'Flower Bouquets',
    rating: 4.7,
    reviewCount: 510,
    inStock: true,
  ),
  Product(
    id: 'g14',
    name: 'Lily Flower Bouquet',
    brand: 'FlowerAura',
    price: 799,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1468327768560-75b778cbb551',
    description: 'Elegant fresh lily bouquet.',
    category: 'Flowers & Gifts',
    subcategory: 'Flower Bouquets',
    rating: 4.6,
    reviewCount: 360,
    inStock: true,
  ),
  Product(
    id: 'g15',
    name: 'Birthday Chocolate Hamper',
    brand: 'IGP',
    price: 1099,
    originalPrice: 1599,
    imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48',
    description: 'Birthday hamper with chocolates and gifts.',
    category: 'Flowers & Gifts',
    subcategory: 'Gift Hampers',
    rating: 4.5,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'g16',
    name: 'Tea Gift Hamper',
    brand: 'The Tea Shelf',
    price: 799,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574',
    description: 'Premium tea gift hamper.',
    category: 'Flowers & Gifts',
    subcategory: 'Gift Hampers',
    rating: 4.4,
    reviewCount: 280,
    inStock: true,
  ),
  Product(
    id: 'g17',
    name: 'Coffee Gift Box',
    brand: 'Blue Tokai',
    price: 899,
    originalPrice: 1299,
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd',
    description: 'Premium coffee gift box.',
    category: 'Flowers & Gifts',
    subcategory: 'Gift Hampers',
    rating: 4.6,
    reviewCount: 310,
    inStock: true,
  ),
  Product(
    id: 'g18',
    name: 'Dark Chocolate Box',
    brand: 'Lindt',
    price: 799,
    originalPrice: 1099,
    imageUrl: 'https://images.unsplash.com/photo-1575377427642-087cf684f29d',
    description: 'Premium dark chocolate box.',
    category: 'Flowers & Gifts',
    subcategory: 'Chocolates',
    rating: 4.8,
    reviewCount: 740,
    inStock: true,
  ),
  Product(
    id: 'g19',
    name: 'Milk Chocolate Collection',
    brand: 'Cadbury',
    price: 599,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b',
    description: 'Assorted milk chocolate collection.',
    category: 'Flowers & Gifts',
    subcategory: 'Chocolates',
    rating: 4.6,
    reviewCount: 810,
    inStock: true,
  ),
  Product(
    id: 'g20',
    name: 'Romantic Greeting Card',
    brand: 'Archies',
    price: 199,
    originalPrice: 299,
    imageUrl: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0',
    description: 'Romantic greeting card.',
    category: 'Flowers & Gifts',
    subcategory: 'Greeting Cards',
    rating: 4.3,
    reviewCount: 210,
    inStock: true,
  ),
  Product(
    id: 'g21',
    name: 'Birthday Greeting Card',
    brand: 'Archies',
    price: 199,
    originalPrice: 299,
    imageUrl: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0',
    description: 'Birthday greeting card.',
    category: 'Flowers & Gifts',
    subcategory: 'Greeting Cards',
    rating: 4.4,
    reviewCount: 290,
    inStock: true,
  ),
  Product(
    id: 'g22',
    name: 'Custom Name Keychain',
    brand: 'IGP',
    price: 249,
    originalPrice: 399,
    imageUrl: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49',
    description: 'Personalized name keychain.',
    category: 'Flowers & Gifts',
    subcategory: 'Personalized Gifts',
    rating: 4.5,
    reviewCount: 330,
    inStock: true,
  ),
  Product(
    id: 'g23',
    name: 'Personalized Cushion',
    brand: 'IGP',
    price: 449,
    originalPrice: 699,
    imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2',
    description: 'Personalized photo cushion.',
    category: 'Flowers & Gifts',
    subcategory: 'Personalized Gifts',
    rating: 4.4,
    reviewCount: 410,
    inStock: true,
  ),
  Product(
    id: 'g24',
    name: 'Rose and Chocolate Combo',
    brand: 'FlowerAura',
    price: 999,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946',
    description: 'Romantic roses and chocolates combo.',
    category: 'Flowers & Gifts',
    subcategory: 'Anniversary Gifts',
    rating: 4.7,
    reviewCount: 470,
    inStock: true,
  ),
  Product(
    id: 'g25',
    name: 'Anniversary Gift Hamper',
    brand: 'Ferns N Petals',
    price: 1399,
    originalPrice: 1999,
    imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48',
    description: 'Premium anniversary gift hamper.',
    category: 'Flowers & Gifts',
    subcategory: 'Anniversary Gifts',
    rating: 4.7,
    reviewCount: 360,
    inStock: true,
  ),
  Product(
    id: 'g26',
    name: 'White Rose Bouquet',
    brand: 'FlowerAura',
    price: 649,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9',
    description: 'Elegant white rose bouquet.',
    category: 'Flowers & Gifts',
    subcategory: 'Flower Bouquets',
    rating: 4.6,
    reviewCount: 420,
    inStock: true,
  ),
  Product(
    id: 'g27',
    name: 'Luxury Chocolate Hamper',
    brand: 'Lindt',
    price: 1299,
    originalPrice: 1799,
    imageUrl: 'https://images.unsplash.com/photo-1575377427642-087cf684f29d',
    description: 'Luxury assorted chocolate hamper.',
    category: 'Flowers & Gifts',
    subcategory: 'Chocolates',
    rating: 4.8,
    reviewCount: 390,
    inStock: true,
  ),
  Product(
    id: 'g28',
    name: 'Congratulations Card',
    brand: 'Archies',
    price: 199,
    originalPrice: 299,
    imageUrl: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0',
    description: 'Congratulations greeting card.',
    category: 'Flowers & Gifts',
    subcategory: 'Greeting Cards',
    rating: 4.2,
    reviewCount: 170,
    inStock: true,
  ),
  Product(
    id: 'g29',
    name: 'Custom Photo Frame',
    brand: 'IGP',
    price: 599,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38',
    description: 'Custom photo frame for gifting.',
    category: 'Flowers & Gifts',
    subcategory: 'Personalized Gifts',
    rating: 4.6,
    reviewCount: 360,
    inStock: true,
  ),
  Product(
    id: 'g30',
    name: 'Premium Celebration Hamper',
    brand: 'Ferns N Petals',
    price: 1599,
    originalPrice: 2299,
    imageUrl: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48',
    description: 'Premium celebration gift hamper.',
    category: 'Flowers & Gifts',
    subcategory: 'Gift Hampers',
    rating: 4.7,
    reviewCount: 290,
    inStock: true,
  ),

  // ============================================================
  // BEAUTY - 30
  // ============================================================

  Product(
    id: 'b1',
    name: 'Professional Makeup Kit',
    brand: 'Maybelline',
    price: 999,
    originalPrice: 1599,
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
    description: 'Complete makeup kit for everyday looks.',
    category: 'Beauty',
    subcategory: 'Makeup',
    rating: 4.4,
    reviewCount: 1200,
    inStock: true,
  ),
  Product(
    id: 'b2',
    name: 'Matte Lipstick',
    brand: 'Lakme',
    price: 399,
    originalPrice: 599,
    imageUrl: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa',
    description: 'Long-lasting matte lipstick.',
    category: 'Beauty',
    subcategory: 'Makeup',
    rating: 4.5,
    reviewCount: 950,
    inStock: true,
  ),
  Product(
    id: 'b3',
    name: 'Foundation',
    brand: 'Maybelline',
    price: 549,
    originalPrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1631214524020-7e18db9a8f92',
    description: 'Lightweight foundation for smooth coverage.',
    category: 'Beauty',
    subcategory: 'Makeup',
    rating: 4.4,
    reviewCount: 720,
    inStock: true,
  ),
  Product(
    id: 'b4',
    name: 'Eyeshadow Palette',
    brand: 'MARS',
    price: 699,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796',
    description: 'Versatile eyeshadow palette.',
    category: 'Beauty',
    subcategory: 'Makeup',
    rating: 4.5,
    reviewCount: 640,
    inStock: true,
  ),
  Product(
    id: 'b5',
    name: 'Face Serum',
    brand: 'Minimalist',
    price: 599,
    originalPrice: 699,
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be',
    description: 'Lightweight skincare serum.',
    category: 'Beauty',
    subcategory: 'Skincare',
    rating: 4.6,
    reviewCount: 1450,
    inStock: true,
  ),
  Product(
    id: 'b6',
    name: 'Vitamin C Serum',
    brand: 'Plum',
    price: 649,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883',
    description: 'Vitamin C serum for daily skincare.',
    category: 'Beauty',
    subcategory: 'Skincare',
    rating: 4.5,
    reviewCount: 980,
    inStock: true,
  ),
  Product(
    id: 'b7',
    name: 'Moisturizing Cream',
    brand: 'Nivea',
    price: 299,
    originalPrice: 449,
    imageUrl: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8',
    description: 'Daily moisturizing cream.',
    category: 'Beauty',
    subcategory: 'Skincare',
    rating: 4.4,
    reviewCount: 850,
    inStock: true,
  ),
  Product(
    id: 'b8',
    name: 'Sunscreen SPF 50',
    brand: 'Minimalist',
    price: 449,
    originalPrice: 599,
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03',
    description: 'Lightweight SPF 50 sunscreen.',
    category: 'Beauty',
    subcategory: 'Skincare',
    rating: 4.6,
    reviewCount: 1300,
    inStock: true,
  ),
  Product(
    id: 'b9',
    name: 'Shampoo',
    brand: 'L’Oreal',
    price: 399,
    originalPrice: 599,
    imageUrl: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d',
    description: 'Nourishing shampoo for healthy hair.',
    category: 'Beauty',
    subcategory: 'Haircare',
    rating: 4.4,
    reviewCount: 870,
    inStock: true,
  ),
  Product(
    id: 'b10',
    name: 'Hair Conditioner',
    brand: 'Dove',
    price: 349,
    originalPrice: 499,
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e',
    description: 'Smoothening hair conditioner.',
    category: 'Beauty',
    subcategory: 'Haircare',
    rating: 4.3,
    reviewCount: 640,
    inStock: true,
  ),
  Product(
    id: 'b11',
    name: 'Hair Serum',
    brand: 'Streax',
    price: 299,
    originalPrice: 449,
    imageUrl: 'https://images.unsplash.com/photo-1527799820374-dcf8f9d8d8cc',
    description: 'Hair serum for smooth and shiny hair.',
    category: 'Beauty',
    subcategory: 'Haircare',
    rating: 4.4,
    reviewCount: 710,
    inStock: true,
  ),
  Product(
    id: 'b12',
    name: 'Body Lotion',
    brand: 'Vaseline',
    price: 299,
    originalPrice: 449,
    imageUrl: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc',
    description: 'Moisturizing body lotion.',
    category: 'Beauty',
    subcategory: 'Body Care',
    rating: 4.5,
    reviewCount: 920,
    inStock: true,
  ),
  Product(
    id: 'b13',
    name: 'Face Wash',
    brand: 'Himalaya',
    price: 199,
    originalPrice: 299,
    imageUrl: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8',
    description: 'Gentle daily face wash.',
    category: 'Beauty',
    subcategory: 'Skincare',
    rating: 4.4,
    reviewCount: 1100,
    inStock: true,
  ),
  Product(
    id: 'b14',
    name: 'Aloe Vera Gel',
    brand: 'Mamaearth',
    price: 249,
    originalPrice: 399,
    imageUrl: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd',
    description: 'Soothing aloe vera gel.',
    category: 'Beauty',
    subcategory: 'Skincare',
    rating: 4.3,
    reviewCount: 760,
    inStock: true,
  ),
  Product(
    id: 'b15',
    name: 'Compact Powder',
    brand: 'Lakme',
    price: 349,
    originalPrice: 499,
    imageUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796',
    description: 'Compact powder for a smooth finish.',
    category: 'Beauty',
    subcategory: 'Makeup',
    rating: 4.4,
    reviewCount: 590,
    inStock: true,
  ),
  Product(
    id: 'b16',
    name: 'Mascara',
    brand: 'Maybelline',
    price: 449,
    originalPrice: 649,
    imageUrl: 'https://images.unsplash.com/photo-1583241800698-e8ab01830a07',
    description: 'Volumizing mascara.',
    category: 'Beauty',
    subcategory: 'Makeup',
    rating: 4.5,
    reviewCount: 680,
    inStock: true,
  ),
  Product(
    id: 'b17',
    name: 'Kajal Pencil',
    brand: 'Lakme',
    price: 199,
    originalPrice: 299,
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
    description: 'Long-lasting kajal pencil.',
    category: 'Beauty',
    subcategory: 'Makeup',
    rating: 4.4,
    reviewCount: 820,
    inStock: true,
  ),
  Product(
    id: 'b18',
    name: 'Blush Palette',
    brand: 'MARS',
    price: 499,
    originalPrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796',
    description: 'Beautiful blush palette.',
    category: 'Beauty',
    subcategory: 'Makeup',
    rating: 4.3,
    reviewCount: 390,
    inStock: true,
  ),
  Product(
    id: 'b19',
    name: 'Night Repair Serum',
    brand: 'Minimalist',
    price: 699,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be',
    description: 'Night serum for skincare routine.',
    category: 'Beauty',
    subcategory: 'Skincare',
    rating: 4.6,
    reviewCount: 710,
    inStock: true,
  ),
  Product(
    id: 'b20',
    name: 'Hydrating Face Mask',
    brand: 'Plum',
    price: 399,
    originalPrice: 599,
    imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881',
    description: 'Hydrating facial mask.',
    category: 'Beauty',
    subcategory: 'Skincare',
    rating: 4.4,
    reviewCount: 420,
    inStock: true,
  ),
  Product(
    id: 'b21',
    name: 'Anti Dandruff Shampoo',
    brand: 'Head & Shoulders',
    price: 349,
    originalPrice: 499,
    imageUrl: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d',
    description: 'Anti-dandruff shampoo.',
    category: 'Beauty',
    subcategory: 'Haircare',
    rating: 4.3,
    reviewCount: 760,
    inStock: true,
  ),
  Product(
    id: 'b22',
    name: 'Hair Mask',
    brand: 'L’Oreal',
    price: 499,
    originalPrice: 699,
    imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e',
    description: 'Deep conditioning hair mask.',
    category: 'Beauty',
    subcategory: 'Haircare',
    rating: 4.5,
    reviewCount: 520,
    inStock: true,
  ),
  Product(
    id: 'b23',
    name: 'Hand Cream',
    brand: 'The Body Shop',
    price: 299,
    originalPrice: 449,
    imageUrl: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b',
    description: 'Moisturizing hand cream.',
    category: 'Beauty',
    subcategory: 'Body Care',
    rating: 4.4,
    reviewCount: 310,
    inStock: true,
  ),
  Product(
    id: 'b24',
    name: 'Body Scrub',
    brand: 'MCaffeine',
    price: 399,
    originalPrice: 599,
    imageUrl: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883',
    description: 'Exfoliating body scrub.',
    category: 'Beauty',
    subcategory: 'Body Care',
    rating: 4.5,
    reviewCount: 470,
    inStock: true,
  ),
  Product(
    id: 'b25',
    name: 'Perfume for Women',
    brand: 'Skinn',
    price: 999,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1541643600914-78b084683601',
    description: 'Elegant floral fragrance.',
    category: 'Beauty',
    subcategory: 'Perfumes',
    rating: 4.6,
    reviewCount: 630,
    inStock: true,
  ),
  Product(
    id: 'b26',
    name: 'Perfume for Men',
    brand: 'Park Avenue',
    price: 699,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1594035910387-fea47794261f',
    description: 'Fresh masculine fragrance.',
    category: 'Beauty',
    subcategory: 'Perfumes',
    rating: 4.4,
    reviewCount: 720,
    inStock: true,
  ),
  Product(
    id: 'b27',
    name: 'Makeup Brush Set',
    brand: 'MARS',
    price: 499,
    originalPrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
    description: 'Professional makeup brush set.',
    category: 'Beauty',
    subcategory: 'Beauty Accessories',
    rating: 4.5,
    reviewCount: 560,
    inStock: true,
  ),
  Product(
    id: 'b28',
    name: 'Beauty Blender Set',
    brand: 'Colorbar',
    price: 299,
    originalPrice: 499,
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
    description: 'Soft makeup blending sponge set.',
    category: 'Beauty',
    subcategory: 'Beauty Accessories',
    rating: 4.4,
    reviewCount: 440,
    inStock: true,
  ),
  Product(
    id: 'b29',
    name: 'Nail Art Kit',
    brand: 'Vega',
    price: 399,
    originalPrice: 699,
    imageUrl: 'https://images.unsplash.com/photo-1604654894610-df63bc536371',
    description: 'Complete nail art kit.',
    category: 'Beauty',
    subcategory: 'Beauty Accessories',
    rating: 4.3,
    reviewCount: 280,
    inStock: true,
  ),
  Product(
    id: 'b30',
    name: 'Premium Beauty Gift Set',
    brand: 'The Body Shop',
    price: 1299,
    originalPrice: 1999,
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
    description: 'Premium beauty products gift set.',
    category: 'Beauty',
    subcategory: 'Beauty Accessories',
    rating: 4.7,
    reviewCount: 350,
    inStock: true,
  ),

  // ============================================================
  // FOOTWEAR - 30
  // ============================================================

  Product(
    id: 'w1',
    name: 'Men Running Shoes',
    brand: 'Nike',
    price: 2499,
    originalPrice: 3999,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
    description: 'Lightweight running shoes.',
    category: 'Footwear',
    subcategory: 'Men',
    rating: 4.5,
    reviewCount: 1200,
    inStock: true,
  ),
  Product(
    id: 'w2',
    name: 'Men Sports Shoes',
    brand: 'Adidas',
    price: 2799,
    originalPrice: 4499,
    imageUrl: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5',
    description: 'Comfortable sports shoes.',
    category: 'Footwear',
    subcategory: 'Men',
    rating: 4.6,
    reviewCount: 980,
    inStock: true,
  ),
  Product(
    id: 'w3',
    name: 'Men Casual Sneakers',
    brand: 'Puma',
    price: 1999,
    originalPrice: 3499,
    imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772',
    description: 'Stylish casual sneakers.',
    category: 'Footwear',
    subcategory: 'Men',
    rating: 4.4,
    reviewCount: 870,
    inStock: true,
  ),
  Product(
    id: 'w4',
    name: 'Men Leather Shoes',
    brand: 'Bata',
    price: 1799,
    originalPrice: 2999,
    imageUrl: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4',
    description: 'Classic formal leather shoes.',
    category: 'Footwear',
    subcategory: 'Men',
    rating: 4.3,
    reviewCount: 650,
    inStock: true,
  ),
  Product(
    id: 'w5',
    name: 'Men Flip Flops',
    brand: 'Sparx',
    price: 399,
    originalPrice: 699,
    imageUrl: 'https://images.unsplash.com/photo-1603487742131-4160ec999306',
    description: 'Comfortable everyday flip flops.',
    category: 'Footwear',
    subcategory: 'Men',
    rating: 4.2,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'w6',
    name: 'Women Sandals',
    brand: 'Bata',
    price: 799,
    originalPrice: 1299,
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2',
    description: 'Stylish sandals for women.',
    category: 'Footwear',
    subcategory: 'Women',
    rating: 4.4,
    reviewCount: 720,
    inStock: true,
  ),
  Product(
    id: 'w7',
    name: 'Women Casual Sneakers',
    brand: 'Puma',
    price: 1999,
    originalPrice: 3299,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
    description: 'Trendy casual sneakers.',
    category: 'Footwear',
    subcategory: 'Women',
    rating: 4.5,
    reviewCount: 830,
    inStock: true,
  ),
  Product(
    id: 'w8',
    name: 'Women Running Shoes',
    brand: 'Nike',
    price: 2999,
    originalPrice: 4999,
    imageUrl: 'https://images.unsplash.com/photo-1552346154-21d32810aba3',
    description: 'Lightweight running shoes for women.',
    category: 'Footwear',
    subcategory: 'Women',
    rating: 4.6,
    reviewCount: 690,
    inStock: true,
  ),
  Product(
    id: 'w9',
    name: 'Women Heels',
    brand: 'Metro',
    price: 1499,
    originalPrice: 2499,
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2',
    description: 'Elegant heels for parties.',
    category: 'Footwear',
    subcategory: 'Women',
    rating: 4.3,
    reviewCount: 510,
    inStock: true,
  ),
  Product(
    id: 'w10',
    name: 'Women Flats',
    brand: 'Bata',
    price: 699,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86',
    description: 'Comfortable everyday flats.',
    category: 'Footwear',
    subcategory: 'Women',
    rating: 4.4,
    reviewCount: 620,
    inStock: true,
  ),
  Product(
    id: 'w11',
    name: 'Kids Sports Shoes',
    brand: 'Skechers',
    price: 1299,
    originalPrice: 1999,
    imageUrl: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2',
    description: 'Comfortable sports shoes for kids.',
    category: 'Footwear',
    subcategory: 'Kids',
    rating: 4.5,
    reviewCount: 490,
    inStock: true,
  ),
  Product(
    id: 'w12',
    name: 'Kids Sneakers',
    brand: 'Puma',
    price: 999,
    originalPrice: 1599,
    imageUrl: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782',
    description: 'Stylish sneakers for children.',
    category: 'Footwear',
    subcategory: 'Kids',
    rating: 4.4,
    reviewCount: 390,
    inStock: true,
  ),
  Product(
    id: 'w13',
    name: 'Kids Sandals',
    brand: 'Bata',
    price: 599,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1603487742131-4160ec999306',
    description: 'Comfortable sandals for kids.',
    category: 'Footwear',
    subcategory: 'Kids',
    rating: 4.3,
    reviewCount: 340,
    inStock: true,
  ),
  Product(
    id: 'w14',
    name: 'Kids School Shoes',
    brand: 'Bata',
    price: 699,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77',
    description: 'Durable school shoes.',
    category: 'Footwear',
    subcategory: 'Kids',
    rating: 4.4,
    reviewCount: 520,
    inStock: true,
  ),
  Product(
    id: 'w15',
    name: 'Men Walking Shoes',
    brand: 'Skechers',
    price: 2999,
    originalPrice: 4499,
    imageUrl: 'https://images.unsplash.com/photo-1539185441755-769473a23570',
    description: 'Comfortable walking shoes.',
    category: 'Footwear',
    subcategory: 'Men',
    rating: 4.6,
    reviewCount: 740,
    inStock: true,
  ),
  Product(
    id: 'w16',
    name: 'Men Formal Loafers',
    brand: 'Clarks',
    price: 2499,
    originalPrice: 3999,
    imageUrl: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4',
    description: 'Premium formal loafers.',
    category: 'Footwear',
    subcategory: 'Men',
    rating: 4.5,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'w17',
    name: 'Men Canvas Shoes',
    brand: 'Campus',
    price: 899,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77',
    description: 'Casual canvas shoes.',
    category: 'Footwear',
    subcategory: 'Men',
    rating: 4.2,
    reviewCount: 510,
    inStock: true,
  ),
  Product(
    id: 'w18',
    name: 'Men Slides',
    brand: 'Adidas',
    price: 999,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1603487742131-4160ec999306',
    description: 'Comfortable slides.',
    category: 'Footwear',
    subcategory: 'Men',
    rating: 4.4,
    reviewCount: 610,
    inStock: true,
  ),
  Product(
    id: 'w19',
    name: 'Women Wedges',
    brand: 'Metro',
    price: 1299,
    originalPrice: 1999,
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2',
    description: 'Stylish wedges for women.',
    category: 'Footwear',
    subcategory: 'Women',
    rating: 4.3,
    reviewCount: 410,
    inStock: true,
  ),
  Product(
    id: 'w20',
    name: 'Women Sports Sneakers',
    brand: 'Skechers',
    price: 2499,
    originalPrice: 3999,
    imageUrl: 'https://images.unsplash.com/photo-1552346154-21d32810aba3',
    description: 'Sports sneakers for active lifestyles.',
    category: 'Footwear',
    subcategory: 'Women',
    rating: 4.6,
    reviewCount: 560,
    inStock: true,
  ),
  Product(
    id: 'w21',
    name: 'Women Kolhapuri Flats',
    brand: 'Inc.5',
    price: 799,
    originalPrice: 1299,
    imageUrl: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86',
    description: 'Traditional Kolhapuri style flats.',
    category: 'Footwear',
    subcategory: 'Women',
    rating: 4.5,
    reviewCount: 380,
    inStock: true,
  ),
  Product(
    id: 'w22',
    name: 'Women Slippers',
    brand: 'Sparx',
    price: 399,
    originalPrice: 699,
    imageUrl: 'https://images.unsplash.com/photo-1603487742131-4160ec999306',
    description: 'Comfortable daily slippers.',
    category: 'Footwear',
    subcategory: 'Women',
    rating: 4.2,
    reviewCount: 460,
    inStock: true,
  ),
  Product(
    id: 'w23',
    name: 'Kids Light Up Shoes',
    brand: 'Skechers',
    price: 1499,
    originalPrice: 2299,
    imageUrl: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2',
    description: 'Fun light-up shoes for kids.',
    category: 'Footwear',
    subcategory: 'Kids',
    rating: 4.6,
    reviewCount: 310,
    inStock: true,
  ),
  Product(
    id: 'w24',
    name: 'Kids Velcro Shoes',
    brand: 'Campus',
    price: 799,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782',
    description: 'Easy-to-wear Velcro shoes.',
    category: 'Footwear',
    subcategory: 'Kids',
    rating: 4.3,
    reviewCount: 280,
    inStock: true,
  ),
  Product(
    id: 'w25',
    name: 'Kids School Sandals',
    brand: 'Bata',
    price: 599,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1603487742131-4160ec999306',
    description: 'Comfortable school sandals.',
    category: 'Footwear',
    subcategory: 'Kids',
    rating: 4.4,
    reviewCount: 350,
    inStock: true,
  ),
  Product(
    id: 'w26',
    name: 'Men Hiking Shoes',
    brand: 'Woodland',
    price: 2999,
    originalPrice: 4499,
    imageUrl: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2',
    description: 'Durable hiking shoes for outdoor activities.',
    category: 'Footwear',
    subcategory: 'Men',
    rating: 4.6,
    reviewCount: 390,
    inStock: true,
  ),
  Product(
    id: 'w27',
    name: 'Women Walking Shoes',
    brand: 'Skechers',
    price: 2699,
    originalPrice: 3999,
    imageUrl: 'https://images.unsplash.com/photo-1539185441755-769473a23570',
    description: 'Comfortable walking shoes for women.',
    category: 'Footwear',
    subcategory: 'Women',
    rating: 4.6,
    reviewCount: 450,
    inStock: true,
  ),
  Product(
    id: 'w28',
    name: 'Kids Rain Boots',
    brand: 'Crocs',
    price: 899,
    originalPrice: 1399,
    imageUrl: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2',
    description: 'Water-resistant rain boots for kids.',
    category: 'Footwear',
    subcategory: 'Kids',
    rating: 4.3,
    reviewCount: 220,
    inStock: true,
  ),
  Product(
    id: 'w29',
    name: 'Men Running Sneakers',
    brand: 'Asics',
    price: 3499,
    originalPrice: 4999,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
    description: 'Performance running sneakers.',
    category: 'Footwear',
    subcategory: 'Men',
    rating: 4.7,
    reviewCount: 620,
    inStock: true,
  ),
  Product(
    id: 'w30',
    name: 'Women Party Heels',
    brand: 'Metro',
    price: 1699,
    originalPrice: 2799,
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2',
    description: 'Elegant party heels.',
    category: 'Footwear',
    subcategory: 'Women',
    rating: 4.5,
    reviewCount: 380,
    inStock: true,
  ),

  // ============================================================
  // KITCHEN - 30
  // ============================================================

  Product(
    id: 'k1',
    name: 'Non Stick Cookware Set',
    brand: 'Prestige',
    price: 1999,
    originalPrice: 2999,
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f',
    description: 'Complete non-stick cookware set.',
    category: 'Kitchen',
    subcategory: 'Cookware',
    rating: 4.5,
    reviewCount: 820,
    inStock: true,
  ),
  Product(
    id: 'k2',
    name: 'Stainless Steel Pressure Cooker',
    brand: 'Hawkins',
    price: 1599,
    originalPrice: 2299,
    imageUrl: 'https://images.unsplash.com/photo-1585515320310-259814833e62',
    description: 'Durable stainless steel pressure cooker.',
    category: 'Kitchen',
    subcategory: 'Cookware',
    rating: 4.6,
    reviewCount: 740,
    inStock: true,
  ),
  Product(
    id: 'k3',
    name: 'Induction Cooktop',
    brand: 'Prestige',
    price: 2199,
    originalPrice: 3299,
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f',
    description: 'Fast and efficient induction cooktop.',
    category: 'Kitchen',
    subcategory: 'Appliances',
    rating: 4.4,
    reviewCount: 650,
    inStock: true,
  ),
  Product(
    id: 'k4',
    name: 'Electric Kettle',
    brand: 'Philips',
    price: 999,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5',
    description: 'Fast boiling electric kettle.',
    category: 'Kitchen',
    subcategory: 'Appliances',
    rating: 4.5,
    reviewCount: 890,
    inStock: true,
  ),
  Product(
    id: 'k5',
    name: 'Mixer Grinder',
    brand: 'Preethi',
    price: 2499,
    originalPrice: 3499,
    imageUrl: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b',
    description: 'Powerful mixer grinder for kitchen use.',
    category: 'Kitchen',
    subcategory: 'Appliances',
    rating: 4.4,
    reviewCount: 710,
    inStock: true,
  ),
  Product(
    id: 'k6',
    name: 'Stainless Steel Bottle',
    brand: 'Milton',
    price: 499,
    originalPrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8',
    description: 'Insulated stainless steel bottle.',
    category: 'Kitchen',
    subcategory: 'Bottles',
    rating: 4.6,
    reviewCount: 1200,
    inStock: true,
  ),
  Product(
    id: 'k7',
    name: 'Insulated Water Bottle',
    brand: 'Cello',
    price: 599,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8',
    description: 'Temperature retaining water bottle.',
    category: 'Kitchen',
    subcategory: 'Bottles',
    rating: 4.5,
    reviewCount: 930,
    inStock: true,
  ),
  Product(
    id: 'k8',
    name: 'Ceramic Coffee Mug',
    brand: 'Home Centre',
    price: 249,
    originalPrice: 399,
    imageUrl: 'https://images.unsplash.com/photo-1514228742587-6b1558fcf93a',
    description: 'Elegant ceramic coffee mug.',
    category: 'Kitchen',
    subcategory: 'Mugs',
    rating: 4.4,
    reviewCount: 480,
    inStock: true,
  ),
  Product(
    id: 'k9',
    name: 'Coffee Mug Set',
    brand: 'Borosil',
    price: 499,
    originalPrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1514228742587-6b1558fcf93a',
    description: 'Set of stylish coffee mugs.',
    category: 'Kitchen',
    subcategory: 'Mugs',
    rating: 4.5,
    reviewCount: 620,
    inStock: true,
  ),
  Product(
    id: 'k10',
    name: 'Glass Storage Container Set',
    brand: 'Borosil',
    price: 899,
    originalPrice: 1399,
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f',
    description: 'Airtight glass storage containers.',
    category: 'Kitchen',
    subcategory: 'Storage Containers',
    rating: 4.6,
    reviewCount: 710,
    inStock: true,
  ),
  Product(
    id: 'k11',
    name: 'Plastic Storage Containers',
    brand: 'Milton',
    price: 499,
    originalPrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f',
    description: 'Food storage container set.',
    category: 'Kitchen',
    subcategory: 'Storage Containers',
    rating: 4.3,
    reviewCount: 590,
    inStock: true,
  ),
  Product(
    id: 'k12',
    name: 'Knife Set',
    brand: 'Victorinox',
    price: 999,
    originalPrice: 1499,
    imageUrl: 'https://images.unsplash.com/photo-1593618998160-e34014e67546',
    description: 'Sharp kitchen knife set.',
    category: 'Kitchen',
    subcategory: 'Kitchen Tools',
    rating: 4.6,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'k13',
    name: 'Kitchen Tool Set',
    brand: 'Prestige',
    price: 699,
    originalPrice: 1099,
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f',
    description: 'Complete kitchen tool set.',
    category: 'Kitchen',
    subcategory: 'Kitchen Tools',
    rating: 4.4,
    reviewCount: 510,
    inStock: true,
  ),
  Product(
    id: 'k14',
    name: 'Chopping Board',
    brand: 'Solimo',
    price: 299,
    originalPrice: 499,
    imageUrl: 'https://images.unsplash.com/photo-1593618998160-e34014e67546',
    description: 'Durable kitchen chopping board.',
    category: 'Kitchen',
    subcategory: 'Kitchen Tools',
    rating: 4.3,
    reviewCount: 340,
    inStock: true,
  ),
  Product(
    id: 'k15',
    name: 'Frying Pan',
    brand: 'Hawkins',
    price: 899,
    originalPrice: 1299,
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f',
    description: 'Non-stick frying pan.',
    category: 'Kitchen',
    subcategory: 'Cookware',
    rating: 4.5,
    reviewCount: 680,
    inStock: true,
  ),
  Product(
    id: 'k16',
    name: 'Deep Cooking Pot',
    brand: 'Prestige',
    price: 1099,
    originalPrice: 1599,
    imageUrl: 'https://images.unsplash.com/photo-1585515320310-259814833e62',
    description: 'Deep cooking pot for family meals.',
    category: 'Kitchen',
    subcategory: 'Cookware',
    rating: 4.4,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'k17',
    name: 'Air Fryer',
    brand: 'Philips',
    price: 6999,
    originalPrice: 9999,
    imageUrl: 'https://images.unsplash.com/photo-1585515320310-259814833e62',
    description: 'Healthy oil-free air fryer.',
    category: 'Kitchen',
    subcategory: 'Appliances',
    rating: 4.6,
    reviewCount: 870,
    inStock: true,
  ),
  Product(
    id: 'k18',
    name: 'Toaster',
    brand: 'Bajaj',
    price: 1299,
    originalPrice: 1999,
    imageUrl: 'https://images.unsplash.com/photo-1585238342024-78d387f4a707',
    description: 'Compact bread toaster.',
    category: 'Kitchen',
    subcategory: 'Appliances',
    rating: 4.3,
    reviewCount: 390,
    inStock: true,
  ),
  Product(
    id: 'k19',
    name: 'Lunch Box',
    brand: 'Milton',
    price: 499,
    originalPrice: 799,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950',
    description: 'Leak-proof lunch box.',
    category: 'Kitchen',
    subcategory: 'Storage',
    rating: 4.5,
    reviewCount: 780,
    inStock: true,
  ),
  Product(
    id: 'k20',
    name: 'Kids Lunch Box',
    brand: 'Cello',
    price: 399,
    originalPrice: 599,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950',
    description: 'Colorful lunch box for kids.',
    category: 'Kitchen',
    subcategory: 'Storage',
    rating: 4.4,
    reviewCount: 520,
    inStock: true,
  ),
  Product(
    id: 'k21',
    name: 'Thermal Flask',
    brand: 'Milton',
    price: 799,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8',
    description: 'Insulated thermal flask.',
    category: 'Kitchen',
    subcategory: 'Bottles',
    rating: 4.6,
    reviewCount: 690,
    inStock: true,
  ),
  Product(
    id: 'k22',
    name: 'Travel Mug',
    brand: 'Borosil',
    price: 599,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1514228742587-6b1558fcf93a',
    description: 'Leak-proof travel coffee mug.',
    category: 'Kitchen',
    subcategory: 'Mugs',
    rating: 4.5,
    reviewCount: 430,
    inStock: true,
  ),
  Product(
    id: 'k23',
    name: 'Glass Coffee Cups',
    brand: 'Borosil',
    price: 699,
    originalPrice: 999,
    imageUrl: 'https://images.unsplash.com/photo-1514228742587-6b1558fcf93a',
    description: 'Elegant glass coffee cup set.',
    category: 'Kitchen',
    subcategory: 'Mugs',
    rating: 4.4,
    reviewCount: 280,
    inStock: true,
  ),
  Product(
    id: 'k24',
    name: 'Spice Container Set',
    brand: 'Milton',
    price: 599,
    originalPrice: 899,
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f',
    description: 'Organized spice storage containers.',
    category: 'Kitchen',
    subcategory: 'Storage Containers',
    rating: 4.5,
    reviewCount: 470,
    inStock: true,
  ),
  Product(
    id: 'k25',
    name: 'Airtight Container Set',
    brand: 'Solimo',
    price: 799,
    originalPrice: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f',
    description: 'Airtight food storage container set.',
    category: 'Kitchen',
    subcategory: 'Storage Containers',
    rating: 4.6,
    reviewCount: 560,
    inStock: true,
  ),
  Product(
    id: 'k26',
    name: 'Peeler and Grater Set',
    brand: 'Prestige',
    price: 299,
    originalPrice: 499,
    imageUrl: 'https://images.unsplash.com/photo-1593618998160-e34014e67546',
    description: 'Useful kitchen peeler and grater set.',
    category: 'Kitchen',
    subcategory: 'Kitchen Tools',
    rating: 4.3,
    reviewCount: 320,
    inStock: true,
  ),
  Product(
    id: 'k27',
    name: 'Silicone Spatula Set',
    brand: 'Solimo',
    price: 399,
    originalPrice: 699,
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f',
    description: 'Heat-resistant silicone spatula set.',
    category: 'Kitchen',
    subcategory: 'Kitchen Tools',
    rating: 4.4,
    reviewCount: 390,
    inStock: true,
  ),
  Product(
    id: 'k28',
    name: 'Cookware Combo Set',
    brand: 'Prestige',
    price: 2499,
    originalPrice: 3999,
    imageUrl: 'https://images.unsplash.com/photo-1585515320310-259814833e62',
    description: 'Complete cookware combo.',
    category: 'Kitchen',
    subcategory: 'Cookware',
    rating: 4.6,
    reviewCount: 610,
    inStock: true,
  ),
  Product(
    id: 'k29',
    name: 'Hand Blender',
    brand: 'Philips',
    price: 1499,
    originalPrice: 2199,
    imageUrl: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b',
    description: 'Powerful hand blender for kitchen use.',
    category: 'Kitchen',
    subcategory: 'Appliances',
    rating: 4.4,
    reviewCount: 450,
    inStock: true,
  ),
  Product(
    id: 'k30',
    name: 'Electric Rice Cooker',
    brand: 'Panasonic',
    price: 1999,
    originalPrice: 2999,
    imageUrl: 'https://images.unsplash.com/photo-1585515320310-259814833e62',
    description: 'Convenient electric rice cooker.',
    category: 'Kitchen',
    subcategory: 'Appliances',
    rating: 4.5,
    reviewCount: 520,
    inStock: true,
  ),
];